version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    restart: always
    env_file: ./keycloak.env
    depends_on:
      - keycloak_db
    volumes:
      - ./import-this-realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "18080:8080"
    command:
      - start-dev
      - --import-realm


  keycloak_db:
    container_name: keycloak_db
    image: mariadb:10.3.26
    restart: always
    volumes:
      - keycloak_db_vol:/var/lib/mysql
    env_file:
      - ./keycloak.env
    ports:
      - "9306:3306"
volumes:
  keycloak_db_vol: